### ISSUE TITLE
怎么联系你呀

### ISSUE THREAD

**Issue by YNG12138** [biubiubiu01/uni-music#6]
有一些问题不太清楚，能联系你问一问吗？

**Comment by biubiubiu01** [comment]
https://ext.dcloud.net.cn/plugin?id=4119  hbuildX插件市场任意赞赏后私聊 加v。

**Comment by biubiubiu01** [comment]
> 有一些问题不太清楚，能联系你问一问吗？

https://ext.dcloud.net.cn/plugin?id=4119 hbuildX插件市场任意赞赏后私聊 加v。

**Comment by YNG12138** [comment]
赞赏了，但是插件市场显示客服系统正在维护，好像私聊不了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "biubiubiu01/uni-music"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 上午9:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [biubiubiu01/uni-music] 怎么联系你呀 (Issue #6)





  
有一些问题不太清楚，能联系你问一问吗？
  
https://ext.dcloud.net.cn/plugin?id=4119 hbuildX插件市场任意赞赏后私聊 加v。

**Comment by biubiubiu01** [comment]
没注意维护了，那你加我v吧,:  gist1013
